name: Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16
          cache: npm
      - name: Install Gulp CLI
        run: npm install gulp-cli
      - name: Install dependencies
        run: npm install
      - name: Lint files
        run: gulp lint
