name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 12.x
          # Set this option if you want the action to check for the latest available version that satisfies the version spec
          check-latest: true

      - name: Setup gulp
        run: npm install gulp-cli
      
      - name: Package UI
        run: gulp bundle
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.0
        with:
          name: ui-bundle
          path: build/ui-bundle.zip
          retention-days: 1
      
      - name: Push bundle
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add build/ui-bundle.zip
          git commit -am "Automated bundle"
          git push
      
      # This step dispatches an event to run the CI workflow of plenty-developers-docs
      - name: Rebuild site
        run: |
          curl -X POST https://api.github.com/repos/plentymarkets/plenty-developers-docs/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          --user 'plentymonkey:${{ secrets.PLENTYMONKEY_TOKEN }}' \
          --data '{"event_type": "UIBundleUpdate", "client_payload": { "repository": "${{ github.repository }}" }}'

  notification: 
    name: Google chat notification
    needs: build
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Google Chat Notification Failure
        if: ${{ needs.build.result == 'failure' }}
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: UI Build
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK_FAILURE }}
          status: ${{ needs.build.result }}
